import math

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
N = len(ALPHABET)

def gcd(a, b):
    """Máximo común divisor (Euclides)."""
    while b:
        a, b = b, a % b
    return a

def affine_encrypt(text, k1, k2):
    """Cifra un texto usando el cifrado afín."""
    if gcd(k1, N) != 1:
        raise ValueError(f"k1={k1} no es válido, debe ser coprimo con {N}.")
    
    result = []
    for char in text.upper():
        if char in ALPHABET:
            i = ALPHABET.index(char)
            cipher_index = (k1 * i + k2) % N
            result.append(ALPHABET[cipher_index])
        else:
            result.append(char)
    return "".join(result)


if __name__ == "__main__":
    k1 = 7
    k2 = 8
    plaintext = "PASOU NCUAR TODEH ORASU HIJON OREGR ESABA OLGAS EINQU IETOY FUEHA STALA ENTRA DADEL PASAD IZONO PUDOB AJARL AOSCU RIDAD LAATE MORIZ OVEIN TEMIN UTOSD ESPUE SSEPR ESENT OENCH APULT EPECE LINGE NIERO ANDRA DEESP OSODE OLGAY PADRE DELNI NOENS EGUID AAPAR ECIER ONPOL ICIAS VIGIL ANTES DELBO SQUEL AABUE LAPAR IENTE SAMIS TADES ASICO MOLAM UCHED UMBRE DECUR IOSOS QUESI EMPRE PAREC EESTA RINVI SIBLE MENTE ALACE CHOEN TODAS PARTE SYQUE SEMAT ERIAL IZACU ANDOS UCEDE ALGOF UERAD ELOCO MUNPE ROTOD OFUEE NVANO NOSEE NCONT RONIN GUNAP ISTAC OMOSI EMPRE LOSUN IFORM ADOSY LOSAG ENTES SECRE TOSTR ATARO NDEIM PEDIR MILAB ORELA DMINI STRAD ORDEL BOSQU EDIRI GIALA INVES TIGAC IONMA NIFES TONOT ENERC ONOCI MIENT ODEQU EEXIS TIERA NINGU NPASA DIZOY ORDEN OAUNA CUADR ILLAE XCAVA RENEL SITIO DONDE LASEN ORAAS EGURA BAQUE DESAP ARECI OSUHI JONOH ALLAM OSSIN ORAIC ESDEF ORMES LACAI DADEL ANOCH EOBLI GOAIN TERRU MPIRL ABUSC APARA REANU DARLA ALAMA NANAS IGUIE NTETO DOENE STEMU NDOES MISTE RIOSO YNOHA YACON TECIM IENTO PORNI MIOQU EPARE ZCAQU EPUED ASERA CLARA DOSAT ISFAC TORIA MENTE MEPRE SENTE ENLAC ASAPA RAINT ERROG ARDEN UEVAC UENTA ALASE NORAL AENCO NTREM UYDES MEJOR ADACO MOSIH UBIER AENVE JECID OVEIN TEANO SENTR ESSEM ANASN OPERD IALAE SPERA NZADE RECUP ERARA SUHIJ OSENO RAAND RADEA LPLAT ICARP ORPRI MERAV EZCON USTED NOJUZ GUEOP ORTUN OPREG UNTAR LECIE RTOSD ETALL ESQUE AHORA CONSI DEROI NDISP ENSAB LESEN PRIME RLUGA RCOMO VESTI AELHO MBREQ UESAL IODEL ATIER RAPAR ALLEV ARSEA RAFAE LITOD EUNIF ORME"
    ciphertext = affine_encrypt(plaintext, k1, k2)
    print(f"Texto original: {plaintext}")
    print(f"Texto cifrado:  {ciphertext}")
