import math

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
N = len(ALPHABET)

def mod_inverse(a, m):
    """Calcula el inverso multiplicativo modular de 'a' respecto a 'm'."""
    try:
        return pow(a, -1, m)
    except ValueError:
        raise ValueError(f"El valor k1={a} no tiene inverso modular con módulo {m}.")

def affine_decrypt(ciphertext, k1, k2):
    """Descifra un texto usando el cifrado afín."""
    if math.gcd(k1, N) != 1:
        raise ValueError(f"k1={k1} no es válido, debe ser coprimo con {N}.")
    
    # Calculamos el inverso de k1
    inv_k1 = mod_inverse(k1, N)
    
    result = []
    for char in ciphertext.upper():
        if char in ALPHABET:
            c = ALPHABET.index(char)
            plain_index = (inv_k1 * (c - k2)) % N
            result.append(ALPHABET[plain_index])
        else:
            result.append(char)
            
    return "".join(result)

if __name__ == "__main__":
    k1 = 7
    k2 = 8
    
    ciphertext = "JIECS VWSIX LCDKF CXIES FMTCV CXKYX KEIPI CHYIE KMVQS MKLCU RSKFI ELIHI KVLXI DIDKH JIEID MBCVC JSDCP ITIXH ICEWS XMDID HIILK OCXMB CZKMV LKOMV SLCED KEJSK EEKJX KEKVL CKVWF IJSHL KJKWK HMVYK VMKXC IVDXI DKKEJ CECDK CHYIU JIDXK DKHVM VCKVE KYSMD IIJIX KWMKX CVJCH MWMIE ZMYMH IVLKE DKHPC EQSKH IIPSK HIJIX MKVLK EIOME LIDKE IEMWC OCHIO SWFKD SOPXK DKWSX MCECE QSKEM KOJXK JIXKW KKELI XMVZM EMPHK OKVLK IHIWK WFCKV LCDIE JIXLK EUQSK EKOIL KXMIH MBIWS IVDCE SWKDK IHYCR SKXID KHCWC OSVJK XCLCD CRSKK VZIVC VCEKK VWCVL XCVMV YSVIJ MELIW COCEM KOJXK HCESV MRCXO IDCEU HCEIY KVLKE EKWXK LCELX ILIXC VDKMO JKDMX OMHIP CXKHI DOMVM ELXID CXDKH PCEQS KDMXM YMIHI MVZKE LMYIW MCVOI VMRKE LCVCL KVKXW CVCWM OMKVL CDKQS KKNME LMKXI VMVYS VJIEI DMBCU CXDKV CISVI WSIDX MHHIK NWIZI XKVKH EMLMC DCVDK HIEKV CXIIE KYSXI PIQSK DKEIJ IXKWM CESFM TCVCF IHHIO CEEMV CXIMW KEDKR CXOKE HIWIM DIDKH IVCWF KCPHM YCIMV LKXXS OJMXH IPSEW IJIXI XKIVS DIXHI IHIOI VIVIE MYSMK VLKLC DCKVK ELKOS VDCKE OMELK XMCEC UVCFI UIWCV LKWMO MKVLC JCXVM OMCQS KJIXK BWIQS KJSKD IEKXI WHIXI DCEIL MERIW LCXMI OKVLK OKJXK EKVLK KVHIW IEIJI XIMVL KXXCY IXDKV SKZIW SKVLI IHIEK VCXIH IKVWC VLXKO SUDKE OKTCX IDIWC OCEMF SPMKX IKVZK TKWMD CZKMV LKIVC EKVLX KEEKO IVIEV CJKXD MIHIK EJKXI VBIDK XKWSJ KXIXI ESFMT CEKVC XIIVD XIDKI HJHIL MWIXJ CXJXM OKXIZ KBWCV SELKD VCTSB YSKCJ CXLSV CJXKY SVLIX HKWMK XLCED KLIHH KEQSK IFCXI WCVEM DKXCM VDMEJ KVEIP HKEKV JXMOK XHSYI XWCOC ZKELM IKHFC OPXKQ SKEIH MCDKH ILMKX XIJIX IHHKZ IXEKI XIRIK HMLCD KSVMR CXOK"
    
    plaintext = affine_decrypt(ciphertext, k1, k2)
    
    print(f"Llave utilizada: a={k1}, b={k2}")
    print(f"Texto descifrado:\n{plaintext}")